name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Use Node.js 19
        uses: actions/setup-node@v1
        with:
          # no support for lts as of now with github actions.
          # issue link : https://github.com/actions/setup-node/issues/26
          # lts/gallium node v19.7.0 (npm v9.5.0)
          node-version: '19.7.0'
      - name: Angular CLI install
        run : npm install -g --silent @angular/cli@14.2.12

      - name: Npm install
        run: npm install

      - name: Run tslint
        run : npx tslint src/**/*.ts

      - name: Run build
        run : npm run build:prod

      - name: check if dist folder exists
        run: |
          if [ -d "dist" ]; then
            echo "Directory dist exists."
          else
            echo "Error: Directory dist does not exists."
            exit 1
          fi


      - name: Deploy to azure static web apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_0FEE35403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true # Set this to true if you do not want to build the app before deploying.
          app_location: "dist" # App source code path


